# clone debian source:      gbp clone $PKG_GIT_URL
# update debian source:     gbp pull
# track upstream source:    git remote add upstream $UPSTREAM_GIT_URL
# check new upstream:       uscan --report
# fetch upstream vcs tags:  git fetch upstream --tags
# import upstream source:   gbp import-orig --uscan
# update package version:   gbp dch -c -D unstable -R
# publish source release:   gbp tag && gbp push
# build package:            gbp buildpackage

[DEFAULT]
debian-branch = main
debian-tag = debian/%(version)s
upstream-branch = upstream
upstream-tag = upstream/%(version)s

[buildpackage]
overlay = True
export-dir = ..

[import-orig]
merge = False
upstream-vcs-tag = %(version)s
