# clone debian source:      gbp clone $PKG_GIT_URL
# update debian source:     gbp pull
# check new upstream:       uscan --report
# import upstream source:   gbp import-orig --uscan
# update package version:   gbp dch -c -D unstable -R
# publish source release:   gbp tag && gbp push
# build package:            gbp buildpackage

[DEFAULT]
upstream-tag = %(version)s
debian-branch = main
upstream-branch = upstream

[buildpackage]
overlay = True
export-dir = ..

[import-orig]
merge = False
